### PR TITLE
Minor fixes in build logic

### PR DESCRIPTION
**Pull request by native-api**
Various noncritical tidbits that have been bugging me. See commit messages for details.

### CODE REVIEW

**Comment by native-api** [comment]
The failures in Linux are due to network problems.

**Comment by native-api** [comment]
Fails for 3.7 in MacOS are a CMake problem. Something changed in 3.7.3 library layout and CMake cannot find the library. The last release was built against 3.7.0.

**Comment by native-api** [comment]
It turns out, CMake 3.9 preinstalled in `xcode8.3` does not have this problem, only later versions do.

**Comment by skvark** [comment]
Thanks. This looks ok, I'll merge if you don't have any additional changes coming in.

**Comment by native-api** [comment]
> if you don't have any additional changes coming in.

Not yet. Not yet. :-)

**Comment by skvark** [comment]
👍 Please create new PR for new changes.

**Pull request merged**
