### PR TITLE
Use native Mac M1 Github Runner for the configuration

### PR DESCRIPTION
**Pull request by asmorkalov**

### CODE REVIEW

**Comment by asmorkalov** [comment]
@fengyuentau please install python 3.12 on Mac M1 runner.

**Comment by fengyuentau** [comment]
@asmorkalov Just done installation via HomeBrew: `brew install python@3.12`.

**Comment by asmorkalov** [comment]
@fengyuentau Some extra action is required on your side:
```
Run python3.12 -m pip install --user --no-cache --force-reinstall wheelhouse/opencv*.whl
  python3.12 -m pip install --user --no-cache --force-reinstall wheelhouse/opencv*.whl
  cd /Users/opencv-cn/GHA-OCV-1/_work/opencv-python/opencv-python/tests
  python3.12 get_build_info.py
  shell: /bin/bash -e {0}
  env:
    OPENCV_TEST_DATA_PATH: /Users/opencv-cn/GHA-OCV-1/_work/opencv-python/opencv-python/opencv_extra/testdata
    PYLINT_TEST_FILE: /Users/opencv-cn/GHA-OCV-1/_work/opencv-python/opencv-python/opencv/samples/python/squares.py
    PIP_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-brew-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-brew packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

Notice:  A new release of pip is available: 23.3.1 -> 23.3.2
Notice:  To update, run: python3.12 -m pip install --upgrade pip
```

**Comment by fengyuentau** [comment]
> @fengyuentau Some extra action is required on your side:
> 
> ```
> Run python3.12 -m pip install --user --no-cache --force-reinstall wheelhouse/opencv*.whl
>   python3.12 -m pip install --user --no-cache --force-reinstall wheelhouse/opencv*.whl
>   cd /Users/opencv-cn/GHA-OCV-1/_work/opencv-python/opencv-python/tests
>   python3.12 get_build_info.py
>   shell: /bin/bash -e {0}
>   env:
>     OPENCV_TEST_DATA_PATH: /Users/opencv-cn/GHA-OCV-1/_work/opencv-python/opencv-python/opencv_extra/testdata
>     PYLINT_TEST_FILE: /Users/opencv-cn/GHA-OCV-1/_work/opencv-python/opencv-python/opencv/samples/python/squares.py
>     PIP_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple
> error: externally-managed-environment
> 
> × This environment is externally managed
> ╰─> To install Python packages system-wide, try brew install
>     xyz, where xyz is the package you are trying to
>     install.
>     
>     If you wish to install a non-brew-packaged Python package,
>     create a virtual environment using python3 -m venv path/to/venv.
>     Then use path/to/venv/bin/python and path/to/venv/bin/pip.
>     
>     If you wish to install a non-brew packaged Python application,
>     it may be easiest to use pipx install xyz, which will manage a
>     virtual environment for you. Make sure you have pipx installed.
> 
> note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
> hint: See PEP 668 for the detailed specification.
> 
> Notice:  A new release of pip is available: 23.3.1 -> 23.3.2
> Notice:  To update, run: python3.12 -m pip install --upgrade pip
> ```

I don't quite get it. What do I need to do?

**Comment by asmorkalov** [comment]
https://github.com/opencv/opencv-python/issues/939

**Pull request merged**
