### PR TITLE
License file fix for #34

### PR DESCRIPTION
**Pull request by glitchassassin**
Moves the license files to package_data instead of data_files

### CODE REVIEW

**Comment by skvark** [comment]
I think it would be better that the licenses stay in the root of this repository. By moving them to cv2 folder Github can't autodetect the license and it's harder to find them when they are "hidden".

No big changes needed, just copy the licenses to the cv2 folder during build process. This has to be done before setup.py is called.

And don't worry about the broken builds, I'm looking into that issue.

**Comment by glitchassassin** [comment]
Updated the travis yml file to copy those license files as part of the `before_install` step - does this work?

**Comment by skvark** [comment]
Yes, that should do it. Could you also add it to the Windows builds? New xcopy line to appveyor/build.cmd should be enough.

**Comment by glitchassassin** [comment]
Of course, forgot that setup.py needs it there either way. 🙄 My bad.

**Comment by skvark** [comment]
No problem and thanks :) I will merge this when I get the builds fixed.

**Pull request merged**
